### ISSUE TITLE
Problemer med nuget-repo-referanse

### ISSUE THREAD

**Issue by JanIvarMoldekleiv** [FINTLabs/Fint.DotNet.Example#2]
Filen nuget.config refererer til <add key="FINT" value="https://api.bintray.com/nuget/fint/nuget" />

Dette fungerer ikke.

**Comment by fsjovatsen** [comment]
@erlingjahr vi har vel flyttet fra Bintray til Nuget. Kan du oppdatere prosjektet slik at @JanIvarMoldekleiv får lastet ned deps'ene?

**Comment by erlingjahr** [comment]
Aaaah! Glemte denne! Stemmer at vi har flyttet alle pakkene fra Bintray og til NuGet. Skal få fixa dette seinest i morra.

**Comment by erlingjahr** [comment]
@JanIvarMoldekleiv Da er referansene oppdatert til å benytte nytt repo for nuget-pakker.
